### ISSUE TITLE
［FR］统计每个app的使用时长

### ISSUE THREAD

**Issue by zwz** [songhanghang/goaway#1]

**Comment by songhanghang** [comment]
调研了下，可以实现，有时间补充这个功能

**Comment by songhanghang** [comment]
已完成，欢迎体验

**Comment by zwz** [comment]
赞
以我所知，iphone上面似乎实现不了这样的功能哦

**Comment by zwz** [comment]
@ songhanghang 另外这个是只针对小米手机的吗？
我是cm的系统，装完进去，启动器不断重启，哈哈哈，不说了，要刷机去了

**Comment by songhanghang** [comment]
不区分系统的，华为，vivo都可以用，猜测可能和你刷的系统有关，能不能提供下log

**Comment by zwz** [comment]
我现在进去就无法进行其他操作了。。。

**Comment by zwz** [comment]
Trebuchet已停止运行

abort message: invalid address or address of corrupt block 0x23 passed to dlfree.
其他信息看不懂
